C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_151.ensight.encas 2.2698 
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_152.ensight.encas 2.19882 
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_153.ensight.encas 2.12784
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_154.ensight.encas 2.05686 
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_155.ensight.encas 1.98588
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_156.ensight.encas 1.9149
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_157.ensight.encas 1.95806
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_158.ensight.encas 2.00122
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_159.ensight.encas 2.04438
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_160.ensight.encas 2.08754
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_161.ensight.encas 2.1307
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_162.ensight.encas 2.07948
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_163.ensight.encas 2.02826
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_164.ensight.encas 1.97704
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_165.ensight.encas 1.92582 
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_166.ensight.encas 1.8746
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_167.ensight.encas 1.86082
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_168.ensight.encas 1.84704
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_169.ensight.encas 1.83326
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_170.ensight.encas 1.81948
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_171.ensight.encas 1.8057
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_172.ensight.encas 1.97418
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_173.ensight.encas 2.14266
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_174.ensight.encas 2.31114
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_175.ensight.encas 2.47962
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_176.ensight.encas 2.6481
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_177.ensight.encas 2.65616
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_178.ensight.encas 2.66422
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_179.ensight.encas 2.67228
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_180.ensight.encas 2.68034
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_181.ensight.encas 2.6884
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_182.ensight.encas 2.63692
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_183.ensight.encas 2.58544
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_184.ensight.encas 2.53396
C:\borland\src\ManhattanProject\Bin\bin\release\NormalizeData.exe C:/borland/data/Manhattan/msg_iop2_run3/full_trans_185.ensight.encas 2.48248